apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentic-primitives-gateway.fullname" . }}-config
  labels:
    {{- include "agentic-primitives-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    allow_server_credentials: {{ .Values.allow_server_credentials }}
    providers:
      {{- .Values.providers | toYaml | nindent 6 }}
